
runtime: python37

handlers:
- url: /images
  static_dir: images

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /styles\.css
  static_files: styles.css
  upload: styles\.css