---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bitstore-app
  description: BITStore AppEngine App
  tags:
    - python
    - bitstore
  annotations:
    github.com/project-slug: broadinstitute/bitstore-app
    backstage.io/source-template: template:default/open-pr-with-catalog-entry
  links:
    - url: https://bitstore.broadinstitute.org/
      title: BITStore
      icon: dashboard
spec:
  type: website
  lifecycle: production
  owner: bits-aviso
  system: bitstore
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: bitstore
  title: BITS Store
  description: |
    BITS Store
  links:
    - url: https://bitstore.broadinstitute.org
      title: BITStore
      icon: dashboard
  tags:
    - bits
    - bits-tools
  annotations:
    github.com/project-slug: broadinstitute/bitstore-app
spec:
  owner: bits-aviso
